config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  # get 'home/index'
  get 'home/about'
    authenticated :user do
      root 'friends#index', as: :authenticated_root
    end
    root 'home#index', as: :root_path
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable
        
        has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [ :edit, :update, :destroy ]

  # GET /friends or /friends.json
  def index
    # @friends = Friend.all
    @friends = current_user.friends.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    # @friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)
    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not Authorized to Edit This Friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :instagram, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.text_field :first_name, class:"form-control", placeholder:"First Name" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :email, class:"form-control", placeholder:"email@exemple.com" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :phone, class:"form-control", placeholder:"(xx) xxxxx-xxxx" %>
  </div>

  <div class="field form-group">
    <%= form.text_field :instagram, class:"form-control", placeholder:"Instagram" %>
  </div>
  <div class="field form-group">
    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value:current_user.id, type: :hidden %>
  </div>
  <br/>
  <div>
    <%= form.submit class:"btn btn-secondary" %>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <h1 class="display-4">
    <%= friend.first_name %>
    <%= friend.last_name %>
  </h1>
  <p class="lead">
    <%= friend.email %>  |
    <%= friend.phone %>  |
    <%= friend.instagram %>
  </p>
  <br/>
</div>

app/views/friends/edit.html.erb
<h1>Editing friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show", @friend, class:"btn btn-secondary" %>
  <%= link_to "Back", friends_path, class:"btn btn-dark" %>
</div>

app/views/friends/index.html.erb
<% if user_signed_in? %>

<table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th class="text-center">Name</th>
      <th class="text-center">Email</th>
      <th class="text-center">Phone</th>
      <th class="text-center">Twitter</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
      
      <tr>
          <td class="text-center"><%= link_to friend.first_name + ' ' + friend.last_name, friend %></td>
          <td class="text-center"><%= friend.email %></td>
          <td class="text-center"><%= friend.phone %></td>
          <td class="text-center"><%= friend.instagram %></td>
          <td class="text-center"><%= link_to 'Delete', friend, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "btn btn-outline-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to "New friend", new_friend_path, class:"btn btn-secondary" %>

<% else %>

<% end %>

app/views/friends/new.html.erb
<h1>Add New friend</h1>
<br/>
<%= render "form", friend: @friend %>

<br/>
<%= link_to "Back", friends_path, class:"btn btn-dark" %>

app/views/friends/show.html.erb
<div class="jumbotron">
  <%= render @friend %>
  <%= link_to "Edit", edit_friend_path(@friend), class:"btn btn-secondary" %>
  <%= link_to "Back", friends_path, class:"btn btn-dark" %>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <%= link_to "Friend App", authenticated_root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
        <li class="nav-item">
            <%= link_to "About Us", home_about_path, class:"nav-link" %>
        </li>

        <% if user_signed_in? %>
            <li class="nav-item">
                <%= link_to "Add Friend", new_friend_path, class:"nav-link" %>
            </li>

            <li class="nav-item">
                <%= link_to "Sign Out", destroy_user_session_path, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"nav-link" %>
            </li>

            <li class="nav-item">
                <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
            </li>
        <% else %>
            <li class="nav-item">
                <%= link_to "Sign Up", new_user_registration_path, data: {tubro_method: :create}, class:"nav-link" %>
            </li>

            <li class="nav-item">
                <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
            </li>
        <% end %>

        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
    </div>
</nav>

app/views/home/about.html.erb
<h1>About Us...</h1>

app/views/home/index.html.erb
<h1>HOME</h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>FirstApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>

  <body>
    <%= render "home/header" %>
    <div class="container">
      <br/>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>

      <% if alert %>
        <%= render 'layouts/alerts' %>
      <% end %>

      <%= yield %>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.3/dist/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.1.3/dist/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>

</html>